import { $ } from '@spcy/lib.model.core';
import * as Core from '@spcy/lib.model.core';
import { Types } from '../../index.schema';

const collections = Core.createSet(Core.Seed.collections.collections, {
  cities: Core.collection('Cities', Types.City),
  regions: Core.collection('Regions', Types.Region),
  countries: Core.collection('Countries', Types.Country)
});

const countries = Core.createSet(collections.countries, {
  Україна: { name: 'Україна' }
});

const regions = Core.createSet(collections.regions, {
  АвтономнаРеспублікаКрим: { name: 'Автономна Республіка Крим', country: $(countries.Україна) },
  Вінницькаобласть: { name: 'Вінницька область', country: $(countries.Україна) },
  Волинськаобласть: { name: 'Волинська область', country: $(countries.Україна) },
  Дніпропетровськаобласть: { name: 'Дніпропетровська область', country: $(countries.Україна) },
  Донецькаобласть: { name: 'Донецька область', country: $(countries.Україна) },
  Житомирськаобласть: { name: 'Житомирська область', country: $(countries.Україна) },
  Закарпатськаобласть: { name: 'Закарпатська область', country: $(countries.Україна) },
  Запорізькаобласть: { name: 'Запорізька область', country: $(countries.Україна) },
  ІваноФранківськаобласть: { name: 'Івано-Франківська область', country: $(countries.Україна) },
  Київськаобласть: { name: 'Київська область', country: $(countries.Україна) },
  Кіровоградськаобласть: { name: 'Кіровоградська область', country: $(countries.Україна) },
  Луганськаобласть: { name: 'Луганська область', country: $(countries.Україна) },
  Львівськаобласть: { name: 'Львівська область', country: $(countries.Україна) },
  Київ: { name: 'м. Київ', country: $(countries.Україна) },
  Севастополь: { name: 'м. Севастополь', country: $(countries.Україна) },
  Миколаївськаобласть: { name: 'Миколаївська область', country: $(countries.Україна) },
  Одеськаобласть: { name: 'Одеська область', country: $(countries.Україна) },
  Полтавськаобласть: { name: 'Полтавська область', country: $(countries.Україна) },
  Рівненськаобласть: { name: 'Рівненська область', country: $(countries.Україна) },
  Сумськаобласть: { name: 'Сумська область', country: $(countries.Україна) },
  Тернопільськаобласть: { name: 'Тернопільська область', country: $(countries.Україна) },
  Харківськаобласть: { name: 'Харківська область', country: $(countries.Україна) },
  Херсонськаобласть: { name: 'Херсонська область', country: $(countries.Україна) },
  Хмельницькаобласть: { name: 'Хмельницька область', country: $(countries.Україна) },
  Черкаськаобласть: { name: 'Черкаська область', country: $(countries.Україна) },
  Чернівецькаобласть: { name: 'Чернівецька область', country: $(countries.Україна) },
  Чернігівськаобласть: { name: 'Чернігівська область', country: $(countries.Україна) }
});

const cities = Core.createSet(collections.cities, {
  Алупка: { name: 'Алупка', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Алушта: { name: 'Алушта', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Армянськ: { name: 'Армянськ', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Бахчисарай: { name: 'Бахчисарай', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Білогірськ: { name: 'Білогірськ', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Джанкой: { name: 'Джанкой', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Євпаторія: { name: 'Євпаторія', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Керч: { name: 'Керч', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Красноперекопськ: {
    name: 'Красноперекопськ',
    region: $(regions.АвтономнаРеспублікаКрим),
    country: $(countries.Україна)
  },
  ЯниКапу: { name: 'Яни Капу', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Саки: { name: 'Саки', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Сімферополь: { name: 'Сімферополь', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  СтарийКрим: { name: 'Старий Крим', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Судак: { name: 'Судак', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Феодосія: { name: 'Феодосія', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Щолкіне: { name: 'Щолкіне', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Ялта: { name: 'Ялта', region: $(regions.АвтономнаРеспублікаКрим), country: $(countries.Україна) },
  Бар: { name: 'Бар', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Бершадь: { name: 'Бершадь', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Вінниця: { name: 'Вінниця', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Гайсин: { name: 'Гайсин', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Гнівань: { name: 'Гнівань', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Жмеринка: { name: 'Жмеринка', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Іллінці: { name: 'Іллінці', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Калинівка: { name: 'Калинівка', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Козятин: { name: 'Козятин', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Ладижин: { name: 'Ладижин', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Липовець: { name: 'Липовець', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  МогилівПодільський: {
    name: 'Могилів-Подільський',
    region: $(regions.Вінницькаобласть),
    country: $(countries.Україна)
  },
  Немирів: { name: 'Немирів', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Погребище: { name: 'Погребище', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Тульчин: { name: 'Тульчин', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Хмільник: { name: 'Хмільник', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Шаргород: { name: 'Шаргород', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Ямпіль: { name: 'Ямпіль', region: $(regions.Вінницькаобласть), country: $(countries.Україна) },
  Берестечко: { name: 'Берестечко', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  ВолодимирВолинський: {
    name: 'Володимир-Волинський',
    region: $(regions.Волинськаобласть),
    country: $(countries.Україна)
  },
  Горохів: { name: 'Горохів', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  КаміньКаширський: { name: 'Камінь-Каширський', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Ківерці: { name: 'Ківерці', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Ковель: { name: 'Ковель', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Луцьк: { name: 'Луцьк', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Любомль: { name: 'Любомль', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Нововолинськ: { name: 'Нововолинськ', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Рожище: { name: 'Рожище', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Устилуг: { name: 'Устилуг', region: $(regions.Волинськаобласть), country: $(countries.Україна) },
  Апостолове: { name: 'Апостолове', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Верхівцеве: { name: 'Верхівцеве', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Верхньодніпровськ: {
    name: 'Верхньодніпровськ',
    region: $(regions.Дніпропетровськаобласть),
    country: $(countries.Україна)
  },
  Вільногірськ: { name: 'Вільногірськ', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Дніпро: { name: 'Дніпро', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  ЖовтіВоди: { name: 'Жовті Води', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Зеленодольськ: { name: 'Зеленодольськ', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Камянське: { name: "Кам'янське", region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  КривийРіг: { name: 'Кривий Ріг', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Марганець: { name: 'Марганець', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Нікополь: { name: 'Нікополь', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Новомосковськ: { name: 'Новомосковськ', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Павлоград: { name: 'Павлоград', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Перещепине: { name: 'Перещепине', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Першотравенськ: { name: 'Першотравенськ', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Підгородне: { name: 'Підгородне', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Покров: { name: 'Покров', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Пятихатки: { name: "П'ятихатки", region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Синельникове: { name: 'Синельникове', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Тернівка: { name: 'Тернівка', region: $(regions.Дніпропетровськаобласть), country: $(countries.Україна) },
  Авдіївка: { name: 'Авдіївка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Амвросіївка: { name: 'Амвросіївка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Бахмут: { name: 'Бахмут', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Білицьке: { name: 'Білицьке', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Білозерське: { name: 'Білозерське', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Бунге: { name: 'Бунге', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Волноваха: { name: 'Волноваха', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Вуглегірськ: { name: 'Вуглегірськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Вугледар: { name: 'Вугледар', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Гірник: { name: 'Гірник', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Горлівка: { name: 'Горлівка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Дебальцеве: { name: 'Дебальцеве', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Добропілля: { name: 'Добропілля', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Докучаєвськ: { name: 'Докучаєвськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Донецьк: { name: 'Донецьк', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Дружківка: { name: 'Дружківка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Єнакієве: { name: 'Єнакієве', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Жданівка: { name: 'Жданівка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Залізне: { name: 'Залізне', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Зугрес: { name: 'Зугрес', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Іловайськ: { name: 'Іловайськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Кальміуське: { name: 'Кальміуське', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Костянтинівка: { name: 'Костянтинівка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Краматорськ: { name: 'Краматорськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Красногорівка: { name: 'Красногорівка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Курахове: { name: 'Курахове', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Лиман: { name: 'Лиман', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Макіївка: { name: 'Макіївка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Маріуполь: { name: 'Маріуполь', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Марїнка: { name: "Мар'їнка", region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Миколаївка: { name: 'Миколаївка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Мирноград: { name: 'Мирноград', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Моспине: { name: 'Моспине', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Новоазовськ: { name: 'Новоазовськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Новогродівка: { name: 'Новогродівка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Покровськ: { name: 'Покровськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Родинське: { name: 'Родинське', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Світлодарськ: { name: 'Світлодарськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Святогірськ: { name: 'Святогірськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Селидове: { name: 'Селидове', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Сіверськ: { name: 'Сіверськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Словянськ: { name: "Слов'янськ", region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Сніжне: { name: 'Сніжне', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Соледар: { name: 'Соледар', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Торецьк: { name: 'Торецьк', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Українськ: { name: 'Українськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Харцизьк: { name: 'Харцизьк', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Хрестівка: { name: 'Хрестівка', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  ЧасівЯр: { name: 'Часів Яр', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Чистякове: { name: 'Чистякове', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Шахтарськ: { name: 'Шахтарськ', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Ясинувата: { name: 'Ясинувата', region: $(regions.Донецькаобласть), country: $(countries.Україна) },
  Андрушівка: { name: 'Андрушівка', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Баранівка: { name: 'Баранівка', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Бердичів: { name: 'Бердичів', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Житомир: { name: 'Житомир', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Коростень: { name: 'Коростень', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Коростишів: { name: 'Коростишів', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Малин: { name: 'Малин', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  НовоградВолинський: {
    name: 'Новоград-Волинський',
    region: $(regions.Житомирськаобласть),
    country: $(countries.Україна)
  },
  Овруч: { name: 'Овруч', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Олевськ: { name: 'Олевськ', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Радомишль: { name: 'Радомишль', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Чуднів: { name: 'Чуднів', region: $(regions.Житомирськаобласть), country: $(countries.Україна) },
  Берегове: { name: 'Берегове', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Виноградів: { name: 'Виноградів', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Іршава: { name: 'Іршава', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Мукачево: { name: 'Мукачево', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Перечин: { name: 'Перечин', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Рахів: { name: 'Рахів', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Свалява: { name: 'Свалява', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Тячів: { name: 'Тячів', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Ужгород: { name: 'Ужгород', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Хуст: { name: 'Хуст', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Чоп: { name: 'Чоп', region: $(regions.Закарпатськаобласть), country: $(countries.Україна) },
  Бердянськ: { name: 'Бердянськ', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Василівка: { name: 'Василівка', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Вільнянськ: { name: 'Вільнянськ', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Гуляйполе: { name: 'Гуляйполе', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Дніпрорудне: { name: 'Дніпрорудне', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Енергодар: { name: 'Енергодар', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Запоріжжя: { name: 'Запоріжжя', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  КамянкаДніпровська: {
    name: "Кам'янка-Дніпровська",
    region: $(regions.Запорізькаобласть),
    country: $(countries.Україна)
  },
  Мелітополь: { name: 'Мелітополь', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Молочанськ: { name: 'Молочанськ', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Оріхів: { name: 'Оріхів', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Пологи: { name: 'Пологи', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Приморськ: { name: 'Приморськ', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Токмак: { name: 'Токмак', region: $(regions.Запорізькаобласть), country: $(countries.Україна) },
  Болехів: { name: 'Болехів', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Бурштин: { name: 'Бурштин', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Галич: { name: 'Галич', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Городенка: { name: 'Городенка', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Долина: { name: 'Долина', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  ІваноФранківськ: {
    name: 'Івано-Франківськ',
    region: $(regions.ІваноФранківськаобласть),
    country: $(countries.Україна)
  },
  Калуш: { name: 'Калуш', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Коломия: { name: 'Коломия', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Косів: { name: 'Косів', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Надвірна: { name: 'Надвірна', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Рогатин: { name: 'Рогатин', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Снятин: { name: 'Снятин', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Тисмениця: { name: 'Тисмениця', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Тлумач: { name: 'Тлумач', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Яремче: { name: 'Яремче', region: $(regions.ІваноФранківськаобласть), country: $(countries.Україна) },
  Березань: { name: 'Березань', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  БілаЦерква: { name: 'Біла Церква', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Богуслав: { name: 'Богуслав', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Бориспіль: { name: 'Бориспіль', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Боярка: { name: 'Боярка', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Бровари: { name: 'Бровари', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Буча: { name: 'Буча', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Васильків: { name: 'Васильків', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Вишгород: { name: 'Вишгород', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Вишневе: { name: 'Вишневе', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Ірпінь: { name: 'Ірпінь', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Кагарлик: { name: 'Кагарлик', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Миронівка: { name: 'Миронівка', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Обухів: { name: 'Обухів', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Переяслав: { name: 'Переяслав', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Припять: { name: "Прип'ять", region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Ржищів: { name: 'Ржищів', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Сквира: { name: 'Сквира', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Славутич: { name: 'Славутич', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Тараща: { name: 'Тараща', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Тетіїв: { name: 'Тетіїв', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Узин: { name: 'Узин', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Українка: { name: 'Українка', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Фастів: { name: 'Фастів', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Чорнобиль: { name: 'Чорнобиль', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Яготин: { name: 'Яготин', region: $(regions.Київськаобласть), country: $(countries.Україна) },
  Благовіщенське: { name: 'Благовіщенське', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Бобринець: { name: 'Бобринець', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Гайворон: { name: 'Гайворон', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Долинська: { name: 'Долинська', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Знамянка: { name: "Знам'янка", region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Кропивницький: { name: 'Кропивницький', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  МалаВиска: { name: 'Мала Виска', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Новомиргород: { name: 'Новомиргород', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Новоукраїнка: { name: 'Новоукраїнка', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Олександрія: { name: 'Олександрія', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Помічна: { name: 'Помічна', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Світловодськ: { name: 'Світловодськ', region: $(regions.Кіровоградськаобласть), country: $(countries.Україна) },
  Алмазна: { name: 'Алмазна', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Алчевськ: { name: 'Алчевськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Антрацит: { name: 'Антрацит', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  БоковоХрустальне: { name: 'Боково-Хрустальне', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Брянка: { name: 'Брянка', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Вознесенівка: { name: 'Вознесенівка', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Гірське: { name: 'Гірське', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Голубівка: { name: 'Голубівка', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Довжанськ: { name: 'Довжанськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Зимогіря: { name: "Зимогір'я", region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Золоте: { name: 'Золоте', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Зоринськ: { name: 'Зоринськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Ірміно: { name: 'Ірміно', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Кадіївка: { name: 'Кадіївка', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Кипуче: { name: 'Кипуче', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Кремінна: { name: 'Кремінна', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Лисичанськ: { name: 'Лисичанськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Луганськ: { name: 'Луганськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Лутугине: { name: 'Лутугине', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Міусинськ: { name: 'Міусинськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Молодогвардійськ: { name: 'Молодогвардійськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Новодружеськ: { name: 'Новодружеськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Олександрівськ: { name: 'Олександрівськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Первомайськ: { name: 'Первомайськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Перевальськ: { name: 'Перевальськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  ПетровоКрасносілля: {
    name: 'Петрово-Красносілля',
    region: $(regions.Луганськаобласть),
    country: $(countries.Україна)
  },
  Попасна: { name: 'Попасна', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Привілля: { name: 'Привілля', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Ровеньки: { name: 'Ровеньки', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Рубіжне: { name: 'Рубіжне', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Сватове: { name: 'Сватове', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Сєвєродонецьк: { name: 'Сєвєродонецьк', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Сорокине: { name: 'Сорокине', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Старобільськ: { name: 'Старобільськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Суходільськ: { name: 'Суходільськ', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Хрустальний: { name: 'Хрустальний', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Щастя: { name: 'Щастя', region: $(regions.Луганськаобласть), country: $(countries.Україна) },
  Белз: { name: 'Белз', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Бібрка: { name: 'Бібрка', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Борислав: { name: 'Борислав', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Броди: { name: 'Броди', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Буськ: { name: 'Буськ', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  ВеликіМости: { name: 'Великі Мости', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Винники: { name: 'Винники', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Глиняни: { name: 'Глиняни', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Городок: { name: 'Городок', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Добромиль: { name: 'Добромиль', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Дрогобич: { name: 'Дрогобич', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Дубляни: { name: 'Дубляни', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Жидачів: { name: 'Жидачів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Жовква: { name: 'Жовква', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Золочів: { name: 'Золочів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  КамянкаБузька: { name: "Кам'янка-Бузька", region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Комарно: { name: 'Комарно', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Львів: { name: 'Львів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Миколаїв: { name: 'Миколаїв', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Моршин: { name: 'Моршин', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Мостиська: { name: 'Мостиська', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  НовийКалинів: { name: 'Новий Калинів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  НовийРозділ: { name: 'Новий Розділ', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Новояворівськ: { name: 'Новояворівськ', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Перемишляни: { name: 'Перемишляни', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Пустомити: { name: 'Пустомити', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  РаваРуська: { name: 'Рава-Руська', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Радехів: { name: 'Радехів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Рудки: { name: 'Рудки', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Самбір: { name: 'Самбір', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Сколе: { name: 'Сколе', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Сокаль: { name: 'Сокаль', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Соснівка: { name: 'Соснівка', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  СтарийСамбір: { name: 'Старий Самбір', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Стебник: { name: 'Стебник', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Стрий: { name: 'Стрий', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  СудоваВишня: { name: 'Судова Вишня', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Трускавець: { name: 'Трускавець', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Турка: { name: 'Турка', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Угнів: { name: 'Угнів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Хирів: { name: 'Хирів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Ходорів: { name: 'Ходорів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Червоноград: { name: 'Червоноград', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Яворів: { name: 'Яворів', region: $(regions.Львівськаобласть), country: $(countries.Україна) },
  Київ: { name: 'Київ', region: $(regions.Київ), country: $(countries.Україна) },
  Інкерман: { name: 'Інкерман', region: $(regions.Севастополь), country: $(countries.Україна) },
  Севастополь: { name: 'Севастополь', region: $(regions.Севастополь), country: $(countries.Україна) },
  Баштанка: { name: 'Баштанка', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  Вознесенськ: { name: 'Вознесенськ', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  МиколаївМ: { name: 'Миколаїв', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  НоваОдеса: { name: 'Нова Одеса', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  НовийБуг: { name: 'Новий Буг', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  Очаків: { name: 'Очаків', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  ПервомайськМ: { name: 'Первомайськ', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  Снігурівка: { name: 'Снігурівка', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  Южноукраїнськ: { name: 'Южноукраїнськ', region: $(regions.Миколаївськаобласть), country: $(countries.Україна) },
  Ананьїв: { name: 'Ананьїв', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Арциз: { name: 'Арциз', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Балта: { name: 'Балта', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Березівка: { name: 'Березівка', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  БілгородДністровський: {
    name: 'Білгород-Дністровський',
    region: $(regions.Одеськаобласть),
    country: $(countries.Україна)
  },
  Біляївка: { name: 'Біляївка', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Болград: { name: 'Болград', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Вилкове: { name: 'Вилкове', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Ізмаїл: { name: 'Ізмаїл', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Кілія: { name: 'Кілія', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Кодима: { name: 'Кодима', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Одеса: { name: 'Одеса', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Подільськ: { name: 'Подільськ', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Рені: { name: 'Рені', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Роздільна: { name: 'Роздільна', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Татарбунари: { name: 'Татарбунари', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Теплодар: { name: 'Теплодар', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Чорноморськ: { name: 'Чорноморськ', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Южне: { name: 'Южне', region: $(regions.Одеськаобласть), country: $(countries.Україна) },
  Гадяч: { name: 'Гадяч', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Глобине: { name: 'Глобине', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  ГорішніПлавні: { name: 'Горішні Плавні', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Гребінка: { name: 'Гребінка', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Заводське: { name: 'Заводське', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Зіньків: { name: 'Зіньків', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Карлівка: { name: 'Карлівка', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Кобеляки: { name: 'Кобеляки', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Кременчук: { name: 'Кременчук', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Лохвиця: { name: 'Лохвиця', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Лубни: { name: 'Лубни', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Миргород: { name: 'Миргород', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Пирятин: { name: 'Пирятин', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Полтава: { name: 'Полтава', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Решетилівка: { name: 'Решетилівка', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Хорол: { name: 'Хорол', region: $(regions.Полтавськаобласть), country: $(countries.Україна) },
  Березне: { name: 'Березне', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Вараш: { name: 'Вараш', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Дубно: { name: 'Дубно', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Дубровиця: { name: 'Дубровиця', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Здолбунів: { name: 'Здолбунів', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Корець: { name: 'Корець', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Костопіль: { name: 'Костопіль', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Острог: { name: 'Острог', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Радивилів: { name: 'Радивилів', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Рівне: { name: 'Рівне', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Сарни: { name: 'Сарни', region: $(regions.Рівненськаобласть), country: $(countries.Україна) },
  Білопілля: { name: 'Білопілля', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Буринь: { name: 'Буринь', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Ворожба: { name: 'Ворожба', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Глухів: { name: 'Глухів', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Дружба: { name: 'Дружба', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Конотоп: { name: 'Конотоп', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Кролевець: { name: 'Кролевець', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Лебедин: { name: 'Лебедин', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Охтирка: { name: 'Охтирка', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Путивль: { name: 'Путивль', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Ромни: { name: 'Ромни', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  СерединаБуда: { name: 'Середина-Буда', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Суми: { name: 'Суми', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Тростянець: { name: 'Тростянець', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Шостка: { name: 'Шостка', region: $(regions.Сумськаобласть), country: $(countries.Україна) },
  Бережани: { name: 'Бережани', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Борщів: { name: 'Борщів', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Бучач: { name: 'Бучач', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Заліщики: { name: 'Заліщики', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Збараж: { name: 'Збараж', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Зборів: { name: 'Зборів', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Копичинці: { name: 'Копичинці', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Кременець: { name: 'Кременець', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Ланівці: { name: 'Ланівці', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Монастириська: { name: 'Монастириська', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Підгайці: { name: 'Підгайці', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Почаїв: { name: 'Почаїв', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Скалат: { name: 'Скалат', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Теребовля: { name: 'Теребовля', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Тернопіль: { name: 'Тернопіль', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Хоростків: { name: 'Хоростків', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Чортків: { name: 'Чортків', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Шумськ: { name: 'Шумськ', region: $(regions.Тернопільськаобласть), country: $(countries.Україна) },
  Балаклія: { name: 'Балаклія', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Барвінкове: { name: 'Барвінкове', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Богодухів: { name: 'Богодухів', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Валки: { name: 'Валки', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Вовчанськ: { name: 'Вовчанськ', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Дергачі: { name: 'Дергачі', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Зміїв: { name: 'Зміїв', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Ізюм: { name: 'Ізюм', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Красноград: { name: 'Красноград', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Купянськ: { name: "Куп'янськ", region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Лозова: { name: 'Лозова', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Люботин: { name: 'Люботин', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Мерефа: { name: 'Мерефа', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Первомайський: { name: 'Первомайський', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Південне: { name: 'Південне', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Харків: { name: 'Харків', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Чугуїв: { name: 'Чугуїв', region: $(regions.Харківськаобласть), country: $(countries.Україна) },
  Берислав: { name: 'Берислав', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  Генічеськ: { name: 'Генічеськ', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  ГолаПристань: { name: 'Гола Пристань', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  Каховка: { name: 'Каховка', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  НоваКаховка: { name: 'Нова Каховка', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  Олешки: { name: 'Олешки', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  Скадовськ: { name: 'Скадовськ', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  Таврійськ: { name: 'Таврійськ', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  Херсон: { name: 'Херсон', region: $(regions.Херсонськаобласть), country: $(countries.Україна) },
  Волочиськ: { name: 'Волочиськ', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  ГородокХ: { name: 'Городок', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Деражня: { name: 'Деражня', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Дунаївці: { name: 'Дунаївці', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Ізяслав: { name: 'Ізяслав', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  КамянецьПодільський: {
    name: "Кам'янець-Подільський",
    region: $(regions.Хмельницькаобласть),
    country: $(countries.Україна)
  },
  Красилів: { name: 'Красилів', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Нетішин: { name: 'Нетішин', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Полонне: { name: 'Полонне', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Славута: { name: 'Славута', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Старокостянтинів: { name: 'Старокостянтинів', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Хмельницький: { name: 'Хмельницький', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Шепетівка: { name: 'Шепетівка', region: $(regions.Хмельницькаобласть), country: $(countries.Україна) },
  Ватутіне: { name: 'Ватутіне', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Городище: { name: 'Городище', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Жашків: { name: 'Жашків', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Звенигородка: { name: 'Звенигородка', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Золотоноша: { name: 'Золотоноша', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Камянка: { name: "Кам'янка", region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Канів: { name: 'Канів', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  КорсуньШевченківський: {
    name: 'Корсунь-Шевченківський',
    region: $(regions.Черкаськаобласть),
    country: $(countries.Україна)
  },
  Монастирище: { name: 'Монастирище', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Сміла: { name: 'Сміла', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Тальне: { name: 'Тальне', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Умань: { name: 'Умань', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Христинівка: { name: 'Христинівка', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Черкаси: { name: 'Черкаси', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Чигирин: { name: 'Чигирин', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Шпола: { name: 'Шпола', region: $(regions.Черкаськаобласть), country: $(countries.Україна) },
  Вашківці: { name: 'Вашківці', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Вижниця: { name: 'Вижниця', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Герца: { name: 'Герца', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Заставна: { name: 'Заставна', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Кіцмань: { name: 'Кіцмань', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Новодністровськ: { name: 'Новодністровськ', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Новоселиця: { name: 'Новоселиця', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Сокиряни: { name: 'Сокиряни', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Сторожинець: { name: 'Сторожинець', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Хотин: { name: 'Хотин', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Чернівці: { name: 'Чернівці', region: $(regions.Чернівецькаобласть), country: $(countries.Україна) },
  Батурин: { name: 'Батурин', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Бахмач: { name: 'Бахмач', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Бобровиця: { name: 'Бобровиця', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Борзна: { name: 'Борзна', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Городня: { name: 'Городня', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Ічня: { name: 'Ічня', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Корюківка: { name: 'Корюківка', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Мена: { name: 'Мена', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Ніжин: { name: 'Ніжин', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  НовгородСіверський: {
    name: 'Новгород-Сіверський',
    region: $(regions.Чернігівськаобласть),
    country: $(countries.Україна)
  },
  Носівка: { name: 'Носівка', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Остер: { name: 'Остер', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Прилуки: { name: 'Прилуки', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Семенівка: { name: 'Семенівка', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Сновськ: { name: 'Сновськ', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) },
  Чернігів: { name: 'Чернігів', region: $(regions.Чернігівськаобласть), country: $(countries.Україна) }
});

export const Seed = {
  collections,
  countries,
  regions,
  cities
};
